package:
  name: cctop
  version: "2016_01_05"

source:
  git_rev: '7eaa81b'
  git_url: https://bitbucket.org/juanlmateo/cctop_standalone.git

requirements:
  run:
    - python
    - bx-python
    - bowtie    

#test:
#  imports:
#    - pyinstrument

test:
  files:
    - phiX.fasta
    - run_test.sh
    - test_input.fasta

about:
  home: https://bitbucket.org/juanlmateo/cctop_standalone
  license_file: LICENSE

