package:
  name: cctop
  version: "2016_01_05"

source:
   git_url: https://bitbucket.org/juanlmateo/cctop_standalone.git
   git_rev: '7eaa81b'

requirements:
  run:
    - bx-python
    - bowtie    


test:
  files:
    - phiX.fasta
    - run_test.sh
    - test_input.fasta


about:
  home: https://bitbucket.org/juanlmateo/cctop_standalone
  license_file: LICENSE

